
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Suba
 */
public class FrmAgregarMaterial extends javax.swing.JFrame {

    private Biblioteca bibliotecaCompartida;

    /**
     * Creates new form FrmAgregarMaterial
     */
    public FrmAgregarMaterial(Biblioteca biblioteca) {
        initComponents();

        this.bibliotecaCompartida = biblioteca;

        //Libro
        lblTituloLibro.setEnabled(false);
        txtTituloLibro.setEnabled(false);

        lblAutorLibro.setEnabled(false);
        txtAutorLibro.setEnabled(false);

        lblNoPaginasLibro.setEnabled(false);
        txtNoPaginasLibro.setEnabled(false);

        lblGeneroLibro.setEnabled(false);
        txtGeneroLibro.setEnabled(false);

        lblCantidadLibro.setEnabled(false);
        txtCantidadLibro.setEnabled(false);

        btnAgregarLibro.setEnabled(false);

        //Revista
        lblTituloRevista.setEnabled(false);
        txtTituloRevista.setEnabled(false);

        lblAutorRevista.setEnabled(false);
        txtAutorRevista.setEnabled(false);

        lblNoEdicionRevista.setEnabled(false);
        txtNoEdicionRevista.setEnabled(false);

        lblMesPubliRevista.setEnabled(false);
        txtMesPubliRevista.setEnabled(false);

        lblCantidadRevista.setEnabled(false);
        txtCantidadRevista.setEnabled(false);

        btnAgregarRevista.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpMaterial = new javax.swing.ButtonGroup();
        lblAutorLibro = new javax.swing.JLabel();
        lblTituloLibro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdLibro = new javax.swing.JRadioButton();
        rdRevista = new javax.swing.JRadioButton();
        lblNoPaginasLibro = new javax.swing.JLabel();
        lblGeneroLibro = new javax.swing.JLabel();
        lblMesPubliRevista = new javax.swing.JLabel();
        lblNoEdicionRevista = new javax.swing.JLabel();
        lblAutorRevista = new javax.swing.JLabel();
        lblTituloRevista = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        txtAutorLibro = new javax.swing.JTextField();
        txtGeneroLibro = new javax.swing.JTextField();
        txtNoPaginasLibro = new javax.swing.JTextField();
        txtTituloRevista = new javax.swing.JTextField();
        txtNoEdicionRevista = new javax.swing.JTextField();
        txtMesPubliRevista = new javax.swing.JTextField();
        txtAutorRevista = new javax.swing.JTextField();
        btnAgregarLibro = new javax.swing.JButton();
        btnAgregarRevista = new javax.swing.JButton();
        lblCantidadLibro = new javax.swing.JLabel();
        txtCantidadLibro = new javax.swing.JTextField();
        lblCantidadRevista = new javax.swing.JLabel();
        txtCantidadRevista = new javax.swing.JTextField();
        btnVolverInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAutorLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblAutorLibro.setText("Autor:");
        lblAutorLibro.setOpaque(true);
        getContentPane().add(lblAutorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 290, 50, 29));

        lblTituloLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblTituloLibro.setText("Titulo:");
        lblTituloLibro.setOpaque(true);
        getContentPane().add(lblTituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 243, 50, 29));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Material");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 78, 256, 75));

        grpMaterial.add(rdLibro);
        rdLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        rdLibro.setText("Libro");
        rdLibro.setOpaque(true);
        rdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLibroActionPerformed(evt);
            }
        });
        getContentPane().add(rdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 184, 140, 41));

        grpMaterial.add(rdRevista);
        rdRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        rdRevista.setText("Revista");
        rdRevista.setOpaque(true);
        rdRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRevistaActionPerformed(evt);
            }
        });
        getContentPane().add(rdRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 184, 142, 41));

        lblNoPaginasLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNoPaginasLibro.setText("Num.Paginas:");
        lblNoPaginasLibro.setOpaque(true);
        getContentPane().add(lblNoPaginasLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 340, 105, 29));

        lblGeneroLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblGeneroLibro.setText("Genero:");
        lblGeneroLibro.setOpaque(true);
        getContentPane().add(lblGeneroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 390, 65, 29));

        lblMesPubliRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblMesPubliRevista.setText("Mes Publi:");
        lblMesPubliRevista.setOpaque(true);
        getContentPane().add(lblMesPubliRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 387, 83, 29));

        lblNoEdicionRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNoEdicionRevista.setText("Num.Edicion:");
        lblNoEdicionRevista.setOpaque(true);
        getContentPane().add(lblNoEdicionRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 339, 105, 29));

        lblAutorRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblAutorRevista.setText("Autor:");
        lblAutorRevista.setOpaque(true);
        getContentPane().add(lblAutorRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 291, 50, 29));

        lblTituloRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblTituloRevista.setText("Titulo:");
        lblTituloRevista.setOpaque(true);
        getContentPane().add(lblTituloRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 243, 50, 29));
        getContentPane().add(txtTituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 243, 140, 29));
        getContentPane().add(txtAutorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 293, 134, 29));
        getContentPane().add(txtGeneroLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 393, 134, 29));
        getContentPane().add(txtNoPaginasLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 343, 134, 29));
        getContentPane().add(txtTituloRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 247, 134, -1));
        getContentPane().add(txtNoEdicionRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 343, 134, -1));
        getContentPane().add(txtMesPubliRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 391, 134, -1));
        getContentPane().add(txtAutorRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 295, 134, -1));

        btnAgregarLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAgregarLibro.setText("Añadir libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 544, 127, -1));

        btnAgregarRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAgregarRevista.setText("Añadir revista");
        btnAgregarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRevistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 544, -1, -1));

        lblCantidadLibro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblCantidadLibro.setText("Cantidad:");
        lblCantidadLibro.setOpaque(true);
        getContentPane().add(lblCantidadLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 446, 77, 29));
        getContentPane().add(txtCantidadLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 449, 134, 29));

        lblCantidadRevista.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblCantidadRevista.setText("Cantidad:");
        lblCantidadRevista.setOpaque(true);
        getContentPane().add(lblCantidadRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 440, 77, 29));
        getContentPane().add(txtCantidadRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 443, 134, 29));

        btnVolverInicio.setBackground(new java.awt.Color(51, 51, 0));
        btnVolverInicio.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setText("<- Volver al inicio");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 78, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suba\\Downloads\\3cfd93dd-4e34-4679-81ba-8d6dbd26adb8.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLibroActionPerformed
        //Libro
        lblTituloLibro.setEnabled(true);
        txtTituloLibro.setEnabled(true);

        lblAutorLibro.setEnabled(true);
        txtAutorLibro.setEnabled(true);

        lblNoPaginasLibro.setEnabled(true);
        txtNoPaginasLibro.setEnabled(true);

        lblGeneroLibro.setEnabled(true);
        txtGeneroLibro.setEnabled(true);

        lblCantidadLibro.setEnabled(true);
        txtCantidadLibro.setEnabled(true);

        btnAgregarLibro.setEnabled(true);

        //Revista
        lblTituloRevista.setEnabled(false);
        txtTituloRevista.setEnabled(false);

        lblAutorRevista.setEnabled(false);
        txtAutorRevista.setEnabled(false);

        lblNoEdicionRevista.setEnabled(false);
        txtNoEdicionRevista.setEnabled(false);

        lblMesPubliRevista.setEnabled(false);
        txtMesPubliRevista.setEnabled(false);

        lblCantidadRevista.setEnabled(false);
        txtCantidadRevista.setEnabled(false);

        btnAgregarRevista.setEnabled(false);


    }//GEN-LAST:event_rdLibroActionPerformed

    private void btnAgregarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRevistaActionPerformed
        agregarNuevaRevista();
    }//GEN-LAST:event_btnAgregarRevistaActionPerformed

    private void agregarNuevaRevista() {
        try {
            //Capturar los datos de los campos de texto
            String titulo = txtTituloRevista.getText();
            String autor = txtAutorRevista.getText();
            String mesPubli = txtMesPubliRevista.getText();

            // Validaciones básicas de campos vacíos
            if (titulo.isEmpty() || autor.isEmpty() || mesPubli.isEmpty()) {
                throw new DatosInvalidosException("Todos los campos deben ser llenados.");
            }

            // Convertir a int, manejando posibles errores de formato
            int numEdicion;
            try {
                numEdicion = Integer.parseInt(txtNoEdicionRevista.getText());
            } catch (NumberFormatException e) {
                throw new DatosInvalidosException("El numero de edicion debe ser un número válido.");
            }

            int cantidad;
            try {
                cantidad = Integer.parseInt(txtCantidadRevista.getText());
            } catch (NumberFormatException e) {
                throw new DatosInvalidosException("La cantidad debe ser un número válido.");
            }

            Revista nuevaRevista = new Revista(titulo, autor, cantidad, numEdicion, mesPubli);

            //Agregar a la biblioteca
            bibliotecaCompartida.agregarMaterial(nuevaRevista);

            //Mensaje de exito o de error
            JOptionPane.showMessageDialog(this, "Libro agregado exitosamente: " + titulo);
        } catch (DatosInvalidosException ex) { // Captura excepción personalizada
            JOptionPane.showMessageDialog(this, "Error de datos: " + ex.getMessage());
        } catch (Exception ex) { // Captura cualquier otra excepción inesperada
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage());
        }

        limpiarCampos();
    }

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        agregarNuevoLibro();
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void rdRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRevistaActionPerformed
        //Revista
        lblTituloRevista.setEnabled(true);
        txtTituloRevista.setEnabled(true);

        lblAutorRevista.setEnabled(true);
        txtAutorRevista.setEnabled(true);

        lblNoEdicionRevista.setEnabled(true);
        txtNoEdicionRevista.setEnabled(true);

        lblMesPubliRevista.setEnabled(true);
        txtMesPubliRevista.setEnabled(true);

        lblCantidadRevista.setEnabled(true);
        txtCantidadRevista.setEnabled(true);

        btnAgregarRevista.setEnabled(true);

        //Libro
        lblTituloLibro.setEnabled(false);
        txtTituloLibro.setEnabled(false);

        lblAutorLibro.setEnabled(false);
        txtAutorLibro.setEnabled(false);

        lblNoPaginasLibro.setEnabled(false);
        txtNoPaginasLibro.setEnabled(false);

        lblGeneroLibro.setEnabled(false);
        txtGeneroLibro.setEnabled(false);

        lblCantidadLibro.setEnabled(false);
        txtCantidadLibro.setEnabled(false);

        btnAgregarLibro.setEnabled(false);
    }//GEN-LAST:event_rdRevistaActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void agregarNuevoLibro() {
        try {
            //Capturar los datos de los campos de texto
            String titulo = txtTituloLibro.getText();
            String autor = txtAutorLibro.getText();
            String genero = txtGeneroLibro.getText();

            // Validaciones básicas de campos vacíos
            if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty()) {
                throw new DatosInvalidosException("Todos los campos deben ser llenados.");
            }

            // Convertir a int, manejando posibles errores de formato
            int cantidad;
            try {
                cantidad = Integer.parseInt(txtCantidadLibro.getText());
            } catch (NumberFormatException e) {
                throw new DatosInvalidosException("La cantidad debe ser un número válido.");
            }

            int numeroPaginas;
            try {
                numeroPaginas = Integer.parseInt(txtNoPaginasLibro.getText());
            } catch (NumberFormatException e) {
                throw new DatosInvalidosException("El número de páginas debe ser un número válido.");
            }

            Libro nuevoLibro = new Libro(titulo, autor, cantidad, numeroPaginas, genero);

            //Agregar a la biblioteca
            bibliotecaCompartida.agregarMaterial(nuevoLibro);

            //Mensaje de exito o de error
            JOptionPane.showMessageDialog(this, "Libro agregado exitosamente: " + titulo);
        } catch (DatosInvalidosException ex) { // Captura excepción personalizada
            JOptionPane.showMessageDialog(this, "Error de datos: " + ex.getMessage());
        } catch (Exception ex) { // Captura cualquier otra excepción inesperada
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage());
        }

        limpiarCampos();
    }

    private void limpiarCampos() {
        txtTituloLibro.setText("");
        txtAutorLibro.setText("");
        txtNoPaginasLibro.setText("");
        txtGeneroLibro.setText("");
        txtCantidadLibro.setText("");

        txtTituloRevista.setText("");
        txtAutorRevista.setText("");
        txtNoEdicionRevista.setText("");
        txtMesPubliRevista.setText("");
        txtCantidadRevista.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnAgregarRevista;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.ButtonGroup grpMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblAutorRevista;
    private javax.swing.JLabel lblCantidadLibro;
    private javax.swing.JLabel lblCantidadRevista;
    private javax.swing.JLabel lblGeneroLibro;
    private javax.swing.JLabel lblMesPubliRevista;
    private javax.swing.JLabel lblNoEdicionRevista;
    private javax.swing.JLabel lblNoPaginasLibro;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JLabel lblTituloRevista;
    private javax.swing.JRadioButton rdLibro;
    private javax.swing.JRadioButton rdRevista;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtAutorRevista;
    private javax.swing.JTextField txtCantidadLibro;
    private javax.swing.JTextField txtCantidadRevista;
    private javax.swing.JTextField txtGeneroLibro;
    private javax.swing.JTextField txtMesPubliRevista;
    private javax.swing.JTextField txtNoEdicionRevista;
    private javax.swing.JTextField txtNoPaginasLibro;
    private javax.swing.JTextField txtTituloLibro;
    private javax.swing.JTextField txtTituloRevista;
    // End of variables declaration//GEN-END:variables
}
