
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Suba
 */
public class FrmPrestarMaterial extends javax.swing.JFrame {

    private Biblioteca bibliotecaCompartida;

    /**
     * Creates new form FrmPrestarMaterial
     */
    public FrmPrestarMaterial(Biblioteca biblioteca) {
        initComponents();
        this.bibliotecaCompartida = biblioteca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPrestar = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prestar Material");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 330, 60));

        btnVolverInicio.setBackground(new java.awt.Color(51, 51, 0));
        btnVolverInicio.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setText("<- Volver al inicio");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 40));

        txtPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrestarActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, 40));

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suba\\Downloads\\prestar.png")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverInicioActionPerformed

    private void txtPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrestarActionPerformed

    }//GEN-LAST:event_txtPrestarActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        prestarMaterial();
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void prestarMaterial() {
        String tituloAPrestar = txtPrestar.getText().trim();

        if (tituloAPrestar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el título del material a prestar.");
            return;
        }

        try {
            // Llama al método prestarMaterial de la instancia local de Biblioteca
            bibliotecaCompartida.prestarMaterial(tituloAPrestar);

            JOptionPane.showMessageDialog(this, "Material '" + tituloAPrestar + "' prestado exitosamente.");
            txtPrestar.setText(""); // Limpia el campo después de la operación

        } catch (MaterialNoEncontradoException ex) {
            // Si el material no se encuentra, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (DatosInvalidosException ex) {
            // Si no hay cantidad disponible para prestar, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            // Captura cualquier otra excepción inesperada
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al prestar el material: " + ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPrestar;
    // End of variables declaration//GEN-END:variables
}
