/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @authors Sebastián Valenzuela López
 *          Cristian Darian Maynez Palma
 *          Angel Iram Garcia Soto
 *          Daniel Dominguez Romero
 */
public class FrmVentana extends javax.swing.JFrame {

    MaterialBibliografico mB;
    private Biblioteca miBiblioteca = new Biblioteca();

    /**
     * Creates new form FrmVentana
     */
    public FrmVentana() {
        initComponents();
        System.out.println("inicio");
    }

    public FrmVentana(Biblioteca biblioteca) {
        biblioteca = miBiblioteca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDevolverMaterial = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnPrestarMaterial = new javax.swing.JButton();
        btnAgregarMaterial = new javax.swing.JButton();
        btnBuscarMaterial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 800));
        setMinimumSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDevolverMaterial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnDevolverMaterial.setText("Devolver Material");
        btnDevolverMaterial.setToolTipText("");
        btnDevolverMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btnDevolverMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        btnInventario.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setToolTipText("");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        btnPrestarMaterial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnPrestarMaterial.setText("Prestar Material");
        btnPrestarMaterial.setToolTipText("");
        btnPrestarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrestarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        btnAgregarMaterial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAgregarMaterial.setText("Agregar Material");
        btnAgregarMaterial.setToolTipText("");
        btnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        btnBuscarMaterial.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnBuscarMaterial.setText("Buscar Material");
        btnBuscarMaterial.setToolTipText("");
        btnBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO a BliblioNuts");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suba\\Downloads\\af4aee72-3de5-4157-990d-a7be395f7e8a.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialActionPerformed

        new FrmAgregarMaterial(miBiblioteca).setVisible(true);

    }//GEN-LAST:event_btnAgregarMaterialActionPerformed

    private void btnBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMaterialActionPerformed
        new FrmBuscarMaterial(miBiblioteca).setVisible(true);

    }//GEN-LAST:event_btnBuscarMaterialActionPerformed

    private void btnDevolverMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverMaterialActionPerformed
        new FrmDevolverMaterial(miBiblioteca).setVisible(true);
    }//GEN-LAST:event_btnDevolverMaterialActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        miBiblioteca.obtenerInventario();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnPrestarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarMaterialActionPerformed
        new FrmPrestarMaterial(miBiblioteca).setVisible(true);
    }//GEN-LAST:event_btnPrestarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnBuscarMaterial;
    private javax.swing.JButton btnDevolverMaterial;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPrestarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
